default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "spam_analysis"
      processes: 1
      threads: 3
    - queues: "training"
      processes: 1
      threads: 3
    - queues: "batching"
      processes: 1
      threads: 3
    - queues: "low_priority"
      processes: 1
      threads: 5
    - queues: "*"
      processes: <%= [ENV.fetch("JOB_CONCURRENCY", "1").to_i - 5, 1].max %>
      threads: 3

test:
  <<: *default

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "spam_analysis"
      processes: 1
      threads: 3
    - queues: "training"
      processes: 1
      threads: 3
    - queues: "batching"
      processes: 1
      threads: 3
    - queues: "low_priority"
      processes: 1
      threads: 5
    - queues: "*"
      processes: <%= [ENV.fetch("JOB_CONCURRENCY", "1").to_i - 5, 1].max %>
      threads: 3
