default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "bot"
      processes: 1
      threads: 5
    - queues: "training"
      processes: 1
      threads: 5
    - queues: "batching"
      processes: 1
      threads: 4
    - queues: "low_priority"
      processes: 1
      threads: 5

test:
  <<: *default

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "bot"
      processes: 2
      threads: 5
    - queues: "training"
      processes: 3
      threads: 5
    - queues: "batching"
      processes: 2
      threads: 4
    - queues: "low_priority"
      processes: 2
      threads: 5
